dist: trusty
language: minimal
# branches:
#   only:      
#   - master
#  except:
#  - legacy
sudo: false
before_install:
  - nvm install node
  - npm --version
  # need to manually update the version (if needed)
  # https://yarnpkg.com/lang/en/docs/install-ci/
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - node_modules
install:
  # - rm -rf ./node_modules # clean up if don't want cache
  - yarn --version
script:
  - yarn --cwd ./frontend install
  - yarn --cwd ./frontend run build
  # - yarn --cwd ./.frontend install --frozen-lockfile;
  - yarn --cwd ./frontend test --testPathIgnorePatterns "<rootDir>/src/__tests__/utils"