version: '3.0'

services:
  sdschedule-database:
    container_name: sdschedule-database
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=password" 
      - "MYSQL_DATABASE=classes"
      - "MYSQL_ROOT_HOST=%"
    volumes:
      - sdschedule-data:/var/lib/mysql
  sdschedule-backend:
    container_name: sdschedule-backend
    build: backend 
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app/"
    depends_on: 
      - sdschedule-database
    environment:
      - "PYTHONUNBUFFERED=0"
  sdschedule-frontend:
    container_name: sdschedule-frontend
    build: frontend
    ports: 
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/public:/app/public"
    depends_on: 
      - sdschedule-backend 
volumes:
  sdschedule-data:
