version: '3.0'

services:
  sdschedule-database:
    container_name: sdschedule-database
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=password" 
      - "MYSQL_DATABASE=classes"
    volumes:
      - "sdschedule-data:/var/lib/mysql"
  sdschedule-backend:
    container_name: sdschedule-backend
    build: backend 
    ports:
      - "5000:5000"
    depends_on: 
      - "sdschedule-database"
    environment:
      - "PYTHONUNBUFFERED=0"
      - "SDSCHEDULE_SCRAPE=${SDSCHEDULE_SCRAPE}"
    volumes:
      - "sdschedule-backend-sources:/app"
  sdschedule-frontend:
    container_name: sdschedule-frontend
    build: frontend
    ports: 
      - "3000:3000"
    depends_on: 
      - "sdschedule-backend"
    volumes:
      - "sdschedule-frontend-sources:/app"
volumes:
  sdschedule-data:
  sdschedule-frontend-sources:
  sdschedule-backend-sources:
